name: Go CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '**'

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.25'
            - name: Format code
              run: go fmt ./...
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.25'
            - name: Build code
              run: go build -v ./...
