name: Renovate

on:
  workflow_dispatch: # 手動実行
  schedule:
    - cron: '0 * * * *' # 定期実行

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # ブランチ作成・更新のため
      pull-requests: write # プルリクエスト作成のため
      issues: write        # Dependency Dashboard (Issue)作成・更新のため
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.11
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
